apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit
  namespace: fluentbit2s3
  labels:
    app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Parsers_File parsers.conf

    @INCLUDE input-*.conf
    @INCLUDE output-*.conf

    @INCLUDE filters.conf

  parsers.conf: |
    [PARSER]
        Name        s3_logs
        Format      json
        Time_Key    requestReceivedTimestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ
        Time_Keep   On

    [PARSER]
        Name        kubernetes-tag
        Format      regex
        Regex       (?<default>.+)\.(?<pt>.+)\.(?<training>.+)

  input-s3logs.conf: |
    [INPUT]
        Name              tail
        Tag               kube.default.pt-job-master-0.training
        Tag_Regex         (?<pt>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<default>[^_]+)_(?<training>.+)-
        Path              /var/log/containers/*.log
        Exclude_Path      /var/log/containers/*_fluentbit2s3_*.log
        Parser            s3_logs
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  60

  output-s3.conf: |
    [OUTPUT]
        Name s3
        Match *
        bucket /model-logging/
        region us-east-1
        use_put_object On
        s3_key_format /$TAG[1]/$TAG[3]/%Y/%m/%d/
        s3_key_format_tag_delimiters . 
        total_file_size 5M
        upload_timeout 1m

    [OUTPUT]
        Name  stdout
        Match *

  filters.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Regex_Parser        kubernetes-tag
        Labels              Off
        Annotations         Off
