apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: fluentbit2s3
  labels:
    k8s-app: fluent-bit
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      app: fluent-bit
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: fluent-bit
        k8s-app: fluent-bit
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - env:
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-creds
                  key: access
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-creds
                  key: secret_access
          image: amazon/aws-for-fluent-bit:2.21.4
          imagePullPolicy: Always
          name: fluent-bit
          volumeMounts:
            - name: fluentbitconfigvol
              mountPath: /etc/fluent-bit/conf/
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
          command: ["/fluent-bit/bin/fluent-bit"]
          args: ["-c", "/etc/fluent-bit/conf/fluent-bit.conf"]
      imagePullSecrets:
        - name: aws-registry
      volumes:
        - name: fluentbitconfigvol
          configMap:
            name: fluent-bit
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
