kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: ./data
        containerPath: /data
    extraPortMappings:
      - containerPort: 8000
        hostPort: 8000
